- name: Remove package (to be able to install needed packages for qemu)
  pacman: 
    name: 
      - iptables
    state: absent
  become: yes

- name: Install qemu-kvm
  pacman: 
    name: 
      - archlinux-keyring
      - qemu-full
      - virt-manager
      - virt-viewer
      - dnsmasq
      - bridge-utils
      - libguestfs
      - ovmf
      - vde2
      - ebtables
      - iptables-nft
      - nftables
    state: present
  become: yes

- name: Remove brltty packages that cause really slow system shutdowns
  pacman: 
    name: 
      - brltty
      - qemu-chardev-baum
    state: absent
    force: yes
  become: yes

#- name: Enable qemu-kvm service
#  systemd:
#    name: libvirtd.service
#    state: enabled
#    enabled: yes
#  become: yes

- name: Start qemu-kvm service
  systemd:
    name: libvirtd.service
    state: started
    enabled: yes
  become: yes

- name: Set the UNIX domain socket group ownership to libvirt
  lineinfile:
    path: /etc/libvirt/libvirtd.conf
    search_string: 'unix_sock_group = ' 
    line: unix_sock_group = "libvirt"
    state: present
  become: yes

- name: Set the UNIX socket permissions for the R/W socket
  lineinfile:
    path: /etc/libvirt/libvirtd.conf
    search_string: 'unix_sock_rw_perms = ' 
    line: unix_sock_rw_perms = "0770"
    state: present
  become: yes

- name: Set the qemu user
  lineinfile:
    path: /etc/libvirt/qemu.conf
    search_string: '#user = "libvirt-qemu"' 
    line: user = "{{ user }}"
    state: present
  become: yes

- name: Set the qemu group
  lineinfile:
    path: /etc/libvirt/qemu.conf
    search_string: '#group = "libvirt-qemu"' 
    line: group = "{{ user }}"
    state: present
  become: yes

- name: adding existing user '{{ user }}' to qemu-kvm group
  user:
    name: '{{ user }}'
    groups: 
      - libvirt
      - kvm
    append: yes
  become: yes

- name: Restart qemu-kvm service
  systemd:
    name: libvirtd.service
    state: restarted
    enabled: yes
  become: yes

- name: Start virt-manager network adapter on boot
  shell: virsh net-autostart default
  #ignore_errors: yes
  become: yes

- name: Ensure hooks directory exists
  file:
    path: /etc/libvirt/hooks 
    state: directory
  become: yes

- name: Generate hooks binary
  template:
    src: qemu.j2
    dest: /etc/libvirt/hooks/qemu
  become: yes

- name: Hooks binary +x
  file: dest=/etc/libvirt/hooks/qemu mode=a+x
  become: yes

- name: Copy systemd service file for qemu nosleep
  copy:
    src: libvirt-nosleep@.service
    dest: /etc/systemd/system/libvirt-nosleep@.service
  become: yes



- name: Copy startup hook
  copy:
    src: vfio-startup.sh
    dest: /bin/vfio-startup.sh
  become: yes

- name: startup hook binary +x
  file: dest=/bin/vfio-startup.sh mode=a+x
  become: yes


- name: Copy end hook
  copy:
    src: vfio-teardown.sh
    dest: /bin/vfio-teardown.sh
  become: yes

- name: end hook binary +x
  file: dest=/bin/vfio-teardown.sh mode=a+x
  become: yes

