- name: Install software-properties-common for virtualbox repo
  apt:
    name:
        - software-properties-common
    state: present
  become: yes

- name: Add virtualbox-2016 apt-key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
  become: yes

- name: Add virtualbox apt-key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present
  become: yes

- name: Get ubuntu version name
  shell: lsb_release -cs
  register: ubuntu_release

- name: Add virtualbox apt repository
  apt_repository:
    repo: 'deb [arch=amd64] https://virtualbox.org/virtualbox/debian {{ ubuntu_release.stdout }} contrib'
    state: present
    filename: virtualbox
  become: yes

- name: Install virtualbox text and merge
  apt:
    name:
        - virtualbox-6.1
    state: present
    update_cache: yes
  become: yes

- name: Check if virtualbox extensions exists
  stat:
    path: "/home/{{ user }}/bin/Oracle_VM_VirtualBox_Extension_Pack-6.1.26.vbox-extpack"
  register: vbox_ext

- name: Download file from a file path
  get_url:
    url: https://download.virtualbox.org/virtualbox/6.1.26/Oracle_VM_VirtualBox_Extension_Pack-6.1.26.vbox-extpack
    dest: "/home/{{ user }}/bin/Oracle_VM_VirtualBox_Extension_Pack-6.1.26.vbox-extpack"
  when: not vbox_ext.stat.exists

- name: Install virtualbox extensions
  shell: "yes | VBoxManage extpack install /home/{{ user }}/bin/Oracle_VM_VirtualBox_Extension_Pack-6.1.26.vbox-extpack"
  when: not vbox_ext.stat.exists
  become: yes


