- name: Install apps that are on repos
  package:
    name: "{{ item }}"
    state: present
  become: yes
  with_items: "{{ bulk_packages }}"

- name: Install yay packages
  include_tasks: arch.yml
  when: distro=="arch"