- name: Import vscodium gpg key
  apt_key:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    state: present
  become: yes

- name: install vscodium repository
  apt_repository:
    repo: deb https://download.vscodium.com/debs vscodium main
    state: present
    filename: vscodium
  become: yes

- name: Update apt repo and cache (sudo apt update)
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install vscodium
  package:
    name:
        - codium
    update_cache: yes
  become: yes