- name: Install calibre on Neon
  include_tasks: neon.yml
  when: distro=="neon"

- name: Install calibre on Arch and Tumbleweed
  include_tasks: arch_tw.yml
  when: (distro=="arch") or (distro=="tw")
