- name: Add element repo on KDE Neon
  include_tasks: element_repo_neon.yml
  when: distro=="neon"


- name: Install element
  package:
    name:
        - element-desktop
    state: present
  become: yes

